### PR TITLE
Fix Python App Workflow

### PR DESCRIPTION
**Pull request by Ajstros**
We would like to add CI Python testing using pytest with the `no_fpga` marked tests. Linting would be a nice bonus, but should not stop the workflow because all usage of the `ok` package that requires an Opal Kelly FrontPanel installation would fail the workflow.

### CODE REVIEW

**Comment by Ajstros** [comment]
This PR now includes the changes from the https://github.com/Ajstros/pyripherals/tree/test_fixes branch which allow the `no_fpga` tests to be run with no `config.yaml` file or no `ep_defines_path` set.

**Review by lucask07 — APPROVED** [review]
This was tested without an ep_defines file and also with an ep_defines file with None for the path. In both cases the _no_fpga_ pytests passed.

**Review by lucask07 — APPROVED** [review]
OK, will have to check the covg_fpga tests to confirm no problems. But this makes sense.

**Review by lucask07 — APPROVED** [review]
This is great and will help with data analysis.

**Review by lucask07 — APPROVED** [review]

**Pull request merged**
